// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction_AccountType int32

const (
	Transaction_BANK        Transaction_AccountType = 0
	Transaction_CREDIT_CARD Transaction_AccountType = 1
)

var Transaction_AccountType_name = map[int32]string{
	0: "BANK",
	1: "CREDIT_CARD",
}

var Transaction_AccountType_value = map[string]int32{
	"BANK":        0,
	"CREDIT_CARD": 1,
}

func (x Transaction_AccountType) String() string {
	return proto.EnumName(Transaction_AccountType_name, int32(x))
}

func (Transaction_AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0, 0}
}

type Transaction struct {
	AccountId            int32                   `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32                 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionDate      int32                   `protobuf:"varint,3,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	Description          string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	FxRate               float32                 `protobuf:"fixed32,5,opt,name=fx_rate,json=fxRate,proto3" json:"fx_rate,omitempty"`
	AccountType          Transaction_AccountType `protobuf:"varint,6,opt,name=account_type,json=accountType,proto3,enum=pb.Transaction_AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Transaction) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetTransactionDate() int32 {
	if m != nil {
		return m.TransactionDate
	}
	return 0
}

func (m *Transaction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Transaction) GetFxRate() float32 {
	if m != nil {
		return m.FxRate
	}
	return 0
}

func (m *Transaction) GetAccountType() Transaction_AccountType {
	if m != nil {
		return m.AccountType
	}
	return Transaction_BANK
}

type Transactions struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type FetchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.Transaction_AccountType", Transaction_AccountType_name, Transaction_AccountType_value)
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*Transactions)(nil), "pb.Transactions")
	proto.RegisterType((*FetchRequest)(nil), "pb.FetchRequest")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xa6, 0xe3, 0x87, 0xf2, 0xba, 0xc0, 0xe8, 0x41, 0x1b, 0x8d, 0x49, 0xb3, 0x53, 0xbd, 0xec,
	0x00, 0x27, 0x2f, 0x26, 0x08, 0x9a, 0x10, 0x13, 0x4d, 0x2a, 0xf7, 0xa5, 0x74, 0x25, 0xee, 0xe0,
	0x56, 0xd7, 0x62, 0xe0, 0xff, 0xf0, 0x0f, 0x36, 0x1b, 0x18, 0x0a, 0xb7, 0xbe, 0xef, 0x7d, 0x3f,
	0xfa, 0xe5, 0xc1, 0xc8, 0x55, 0xb2, 0xb0, 0x52, 0xb9, 0xbc, 0x2c, 0x12, 0x53, 0x95, 0xae, 0x24,
	0x81, 0x59, 0xc5, 0xbf, 0x01, 0xe0, 0xe5, 0x71, 0x43, 0xee, 0x00, 0xa4, 0x52, 0xe5, 0xa6, 0x70,
	0x69, 0x9e, 0x51, 0xc4, 0x10, 0xef, 0x8a, 0xfe, 0x01, 0x59, 0x64, 0xe4, 0x0a, 0x7a, 0xf2, 0xab,
	0x7e, 0xd3, 0x80, 0x21, 0x1e, 0x88, 0xc3, 0x44, 0xee, 0x21, 0xf2, 0xfc, 0xd3, 0x4c, 0x3a, 0x4d,
	0xdb, 0x8d, 0x78, 0xe8, 0xe1, 0x73, 0xe9, 0x34, 0x61, 0x80, 0x33, 0x6d, 0x55, 0x95, 0x9b, 0x1a,
	0xa2, 0x1d, 0x86, 0x78, 0x5f, 0xf8, 0x10, 0xb9, 0x86, 0x8b, 0xf5, 0x36, 0xad, 0x6a, 0x8f, 0xee,
	0x3e, 0x65, 0xbd, 0x15, 0xb5, 0xf4, 0x11, 0xc2, 0xff, 0xcf, 0xb9, 0x9d, 0xd1, 0xb4, 0xc7, 0x10,
	0x1f, 0x8c, 0x6f, 0x13, 0xb3, 0x4a, 0xbc, 0x0e, 0xc9, 0x74, 0xcf, 0x59, 0xee, 0x8c, 0x16, 0x58,
	0x1e, 0x87, 0x98, 0x03, 0xf6, 0x76, 0xe4, 0x12, 0x3a, 0x4f, 0xd3, 0xb7, 0xd7, 0xa8, 0x45, 0x86,
	0x80, 0x67, 0xe2, 0x79, 0xbe, 0x58, 0xa6, 0xb3, 0xa9, 0x98, 0x47, 0x28, 0x9e, 0x41, 0xe8, 0x39,
	0x5a, 0x32, 0x81, 0xd0, 0xeb, 0x61, 0x29, 0x62, 0x6d, 0x8e, 0xc7, 0xc3, 0xb3, 0x64, 0x71, 0x42,
	0x8a, 0x07, 0x10, 0xbe, 0x68, 0xa7, 0x3e, 0x85, 0xfe, 0xde, 0x68, 0xeb, 0xc6, 0xef, 0x40, 0x3c,
	0xf2, 0x87, 0xae, 0x7e, 0x72, 0xa5, 0xc9, 0x03, 0x8c, 0x1a, 0xd6, 0x49, 0x5e, 0x54, 0x3b, 0xfb,
	0xe2, 0x9b, 0xe8, 0x2c, 0xcb, 0xc6, 0xad, 0x55, 0xaf, 0xb9, 0xe3, 0xe4, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x32, 0x7c, 0x15, 0xbf, 0xdc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	FetchTransactions(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*Transactions, error)
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) FetchTransactions(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*Transactions, error) {
	out := new(Transactions)
	err := c.cc.Invoke(ctx, "/pb.TransactionService/FetchTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	FetchTransactions(context.Context, *FetchRequest) (*Transactions, error)
}

// UnimplementedTransactionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (*UnimplementedTransactionServiceServer) FetchTransactions(ctx context.Context, req *FetchRequest) (*Transactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTransactions not implemented")
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_FetchTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FetchTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TransactionService/FetchTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FetchTransactions(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTransactions",
			Handler:    _TransactionService_FetchTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
