# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import transaction_pb2 as transaction__pb2


class TransactionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FetchTransactions = channel.unary_unary(
        '/pb.TransactionService/FetchTransactions',
        request_serializer=transaction__pb2.FetchRequest.SerializeToString,
        response_deserializer=transaction__pb2.Transactions.FromString,
        )


class TransactionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FetchTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransactionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FetchTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.FetchTransactions,
          request_deserializer=transaction__pb2.FetchRequest.FromString,
          response_serializer=transaction__pb2.Transactions.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.TransactionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
